### ISSUE TITLE
support for room basis (BB, HB, FB, RO)

### ISSUE THREAD

**Issue by astroanu** [Roomify/rooms#93]
how do i add room prices per basis.. say i have a "suite" and it has different prices for "bed and breakfast", "half board" and "full board".  and each prices needs to change based on single, double and triple.

**Comment by astroanu** [comment]
nobody?

**Comment by acrollet** [comment]
@astroanu the simplest way would be to make the cheapest price the base price, and add options for e.g. half board and full board. If this will not completely meet your needs, you'll want to have a look at hook_rooms_price_modifier_alter() (documented in modules/rooms_booking/rooms_booking.api.php)

**Comment by astroanu** [comment]
i did try. but the calculated values seems to be adding up.. :(

ex: if the user checked both bb and fb it sums the values instead of showing just one.

I think this is a must have feature for this module.

**Comment by cecrs** [comment]
Are you adding the half board example option at the full cost of the room?  If so, it will calculate the room base price + the cost of the option.  Assuming that you have each option priced as the _additional_ cost per night, not as the full cost of the room+board, it should work.

**Comment by astroanu** [comment]
you see, room basis is not an option. a person cannot choose both BB and HB. he needs to choose one. so there should be check boxes on the booking page rather than radio boxes. or wont make any sense.
